### ISSUE TITLE
DID Methods, url is broken

### ISSUE THREAD

**Issue by ydennisy** [w3c-ccg/did-spec#54] opened 2018-02-26 18:03 UTC
The page referenced in the [DID v0.9 Draft](https://w3c-ccg.github.io/did-spec/) as a DID Method Registry page is broken:
https://w3c-ccg.github.io/did-spec/did-methods.html

**Comment by msporny** [comment] 2018-02-26 18:12
Duplicate of https://github.com/w3c-ccg/did-spec/issues/53.

**Closed by msporny** 2018-02-26 18:12 UTC
