### ISSUE TITLE
[URIs, URLs, and URNs] "DIDs have a foundation in URLs" is confusing because DIDs aren't URLs

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#156] opened 2019-01-18 00:25 UTC
In https://w3c-ccg.github.io/did-spec/#uris-urls-and-urns, it states...

> DIDs have a foundation in URLs, so it's important to understand...

This is interesting history but the wording of this sentenceis  confuding.  It leads the reader to believe that DIDs are URLs. See https://github.com/w3c-ccg/did-spec/issues/155

**Comment by jandrieu** [comment] 2019-01-18 01:48
Yes. DIDs are URLs. See my other comments.

**Comment by dmitrizagidulin** [comment] 2019-01-24 15:44
:+1:, I propose closing this issue as duplicate of #155.

**Comment by mwherman2000** [comment] 2019-01-24 15:48
> 👍, I propose closing this issue as duplicate of #155.

Please don't close this.  _This specific issue is about specific wording in the DID spec that needs to be changed._  It's related to #155 but different.

**Closed** 2019-03-03 15:21 UTC
Labels: clarify
